/**
 * types/index.ts - TypeScript Type Definitions
 * 
 * This file contains all custom TypeScript types and interfaces used
 * throughout the My Mind application.
 * 
 * Type Philosophy:
 * - Explicit over implicit (better IDE support)
 * - Interface for objects (allows extension)
 * - Type alias for unions (readonly)
 * - Recursive types where appropriate (Task subtasks)
 * 
 * @module types
 */

/**
 * NotionColor Type
 * 
 * Represents all available task colors, matching Notion's color palette.
 * 
 * Color Psychology:
 * - gray: Neutral, low priority, default
 * - brown: Earthy, stable, routine tasks
 * - orange: Energetic, creative, brainstorming
 * - yellow: Bright, attention-grabbing, important
 * - green: Calm, success, growth-related
 * - blue: Professional, default, organizational (DEFAULT)
 * - purple: Creative, strategic, long-term
 * - pink: Personal, relationship-related, fun
 * - red: Urgent, critical, high-priority
 * 
 * Usage:
 * - Tasks have one color (stored in Task.color)
 * - Subtasks inherit parent color (progressive lightening)
 * - Color selection in ColorPalette component
 * - Color mapping in utils/colors.ts
 * 
 * Type: Union type (not enum) for:
 * - Better type safety
 * - Easier serialization to JSON
 * - Direct string comparison
 * 
 * @type {string}
 */
export type NotionColor =
  | "gray"     // Neutral gray tones
  | "brown"    // Brown/tan tones
  | "orange"   // Orange tones
  | "yellow"   // Yellow tones
  | "green"    // Green tones
  | "blue"     // Blue tones (default)
  | "purple"   // Purple tones
  | "pink"     // Pink tones
  | "red";     // Red tones

/**
 * Task Interface
 * 
 * Represents a single task in the hierarchical todo system.
 * Tasks can contain other tasks (subtasks), creating a tree structure.
 * 
 * RECURSIVE STRUCTURE:
 * - Each task has a subtasks array (Task[])
 * - Each subtask is also a Task
 * - Creates unlimited nesting (capped at 3 in UI)
 * 
 * DATA MODEL:
 * - Top-level tasks have x, y positions on canvas
 * - Subtasks have x=0, y=0 (positioned relative to parent)
 * - parentId tracks parent-child relationships
 * 
 * STATE MANAGEMENT:
 * - Stored in App.tsx state as Task[]
 * - Persisted to Supabase as JSON
 * - Manipulated immutably (spread operators)
 * 
 * @interface
 */
export interface Task {
  /**
   * Unique identifier for this task
   * 
   * Generated by: Math.random().toString(36).substring(2, 9)
   * Format: Random alphanumeric string (e.g., "a7s9d2f")
   * Length: 7 characters
   * 
   * Used for:
   * - React keys in lists
   * - Finding tasks in tree
   * - Drag-and-drop item identification
   * - Parent-child relationships
   * 
   * Note: Not cryptographically secure, but sufficient for client-side IDs.
   * In production, backend would generate UUIDs.
   */
  id: string;

  /**
   * Display title of the task
   * 
   * Constraints:
   * - Non-empty (validation in forms)
   * - Trimmed of whitespace
   * - No length limit (could add max 200 chars in production)
   * 
   * Display:
   * - Shown in TaskCard component
   * - Editable inline (click edit icon)
   * - Searchable via search algorithm
   * 
   * Examples:
   * - "Buy groceries"
   * - "Finish project proposal"
   * - "Call dentist"
   */
  title: string;

  /**
   * Task color from Notion palette
   * 
   * Purpose:
   * - Visual organization (color-code by category)
   * - Hierarchy indication (subtasks lightened)
   * - Aesthetic appeal
   * 
   * Inheritance:
   * - Top-level: User-selected from ColorPalette
   * - Subtasks: Inherit parent's color
   * - Visual: Progressive white overlay for nesting
   * 
   * Default: "blue" (chosen for professional appearance)
   * 
   * See: NotionColor type for all options
   * See: utils/colors.ts for color definitions
   */
  color: NotionColor;

  /**
   * X position on infinite canvas (in pixels)
   * 
   * Usage:
   * - Top-level tasks: Canvas position (draggable)
   * - Subtasks: Always 0 (positioned relative to parent)
   * 
   * Coordinate System:
   * - Origin (0, 0): Top-left of canvas
   * - Positive X: Right
   * - Unlimited range (infinite canvas)
   * 
   * Default for new tasks:
   * - window.innerWidth / 2 - 160 (centered)
   * 
   * Modified by:
   * - Dragging on canvas
   * - Dropping from subtask to canvas
   */
  x: number;

  /**
   * Y position on infinite canvas (in pixels)
   * 
   * Usage:
   * - Top-level tasks: Canvas position (draggable)
   * - Subtasks: Always 0 (positioned relative to parent)
   * 
   * Coordinate System:
   * - Origin (0, 0): Top-left of canvas
   * - Positive Y: Down
   * - Unlimited range (infinite canvas)
   * 
   * Default for new tasks:
   * - tasks.length * 120 + 50 (vertical stack)
   * 
   * Modified by:
   * - Dragging on canvas
   * - Dropping from subtask to canvas
   */
  y: number;

  /**
   * Completion status
   * 
   * True: Task is completed
   * False: Task is not completed (default)
   * 
   * Visual Feedback:
   * - Checkmark in checkbox when true
   * - Strikethrough text when true
   * - Reduced opacity when true
   * 
   * Behavior:
   * - Toggle via checkbox click
   * - Independent for each task (parent/child not linked)
   * 
   * Future Enhancement:
   * - Auto-complete parent when all subtasks complete
   * - Completion date tracking
   * - Statistics (% complete)
   */
  completed: boolean;

  /**
   * Collapse state for subtasks
   * 
   * True: Subtasks are hidden
   * False: Subtasks are visible (default)
   * 
   * Toggle Method:
   * - Double-click on task card
   * - Custom detection (300ms window)
   * 
   * Visual:
   * - No indicator when collapsed (future: chevron icon)
   * - Subtasks completely hidden
   * - Parent remains visible
   * 
   * Purpose:
   * - Reduce visual clutter
   * - Focus on specific branch
   * - Manage large task trees
   * 
   * Future Enhancement:
   * - Remember collapsed state per user
   * - Collapse all / expand all buttons
   */
  collapsed: boolean;

  /**
   * Array of child tasks (recursive)
   * 
   * CRITICAL: This is what makes Task a recursive type!
   * 
   * Structure:
   * - Empty array: No subtasks (leaf node)
   * - Array of Tasks: This task has children
   * - Each child can have its own subtasks
   * 
   * Max Depth: 3 levels (enforced in UI)
   * - Level 0: Top-level task
   * - Level 1: Subtask
   * - Level 2: Sub-subtask
   * - Level 3: Blocked (canAddSubtask = false)
   * 
   * Operations:
   * - Add: Push new task to array
   * - Remove: Filter out task by ID
   * - Reorder: Not implemented (could add drag-to-reorder)
   * 
   * Rendering:
   * - TaskCard recursively renders each subtask
   * - Indentation increases with level
   * - Progressive lightening with white overlay
   * 
   * Example:
   * {
   *   id: "abc123",
   *   title: "Launch Product",
   *   subtasks: [
   *     {
   *       id: "def456",
   *       title: "Build Website",
   *       subtasks: [
   *         {
   *           id: "ghi789",
   *           title: "Design Homepage",
   *           subtasks: []
   *         }
   *       ]
   *     }
   *   ]
   * }
   */
  subtasks: Task[];

  /**
   * Parent task ID (optional)
   * 
   * Purpose:
   * - Track parent-child relationships
   * - Enable "move to parent" feature (future)
   * - Breadcrumb navigation (future)
   * 
   * Value:
   * - undefined: Top-level task (no parent)
   * - string: ID of parent task
   * 
   * Maintenance:
   * - Set when adding subtask
   * - Set when dropping task onto another
   * - Cleared when promoting to top-level
   * 
   * Note: Somewhat redundant (tree structure already implies parent),
   * but useful for certain operations.
   * 
   * Future Use:
   * - Prevent circular references (check ancestors)
   * - Breadcrumb: "Project > Phase 1 > Task A"
   * - "Move up" button (promote to parent's level)
   */
  parentId?: string;
}

/**
 * USAGE EXAMPLES:
 * 
 * 1. Creating a new top-level task:
 * ```typescript
 * const newTask: Task = {
 *   id: generateId(),
 *   title: "Buy groceries",
 *   color: "blue",
 *   x: 100,
 *   y: 100,
 *   completed: false,
 *   collapsed: false,
 *   subtasks: [],
 * };
 * ```
 * 
 * 2. Creating a subtask:
 * ```typescript
 * const newSubtask: Task = {
 *   id: generateId(),
 *   title: "Buy milk",
 *   color: "blue",  // Inherits parent color
 *   x: 0,           // Subtasks use relative positioning
 *   y: 0,
 *   completed: false,
 *   collapsed: false,
 *   subtasks: [],
 *   parentId: parentTask.id,
 * };
 * 
 * parentTask.subtasks.push(newSubtask);
 * ```
 * 
 * 3. Finding a task recursively:
 * ```typescript
 * function findTask(tasks: Task[], id: string): Task | null {
 *   for (const task of tasks) {
 *     if (task.id === id) return task;
 *     const found = findTask(task.subtasks, id);
 *     if (found) return found;
 *   }
 *   return null;
 * }
 * ```
 * 
 * 4. Counting total tasks (including subtasks):
 * ```typescript
 * function countTasks(tasks: Task[]): number {
 *   return tasks.reduce((count, task) => 
 *     count + 1 + countTasks(task.subtasks), 0
 *   );
 * }
 * ```
 */

/**
 * REMOVED TYPES (v2.0.0):
 * 
 * Previously, we had a TodoList interface:
 * 
 * interface TodoList {
 *   id: string;
 *   name: string;
 *   tasks: Task[];
 * }
 * 
 * This was removed when we simplified the app to a single task
 * collection per user (removed lists feature).
 * 
 * See: Documentation.md, Phase 7-8 for details
 */
